


import streamlit as st
import pandas as pd
import joblib

# Load the trained pipeline
model = joblib.load('fraud_detection_pipeline.pkl')

st.title("Credit Card Fraud Detection")

# Define category options
category_options = [
    'personal_care', 'health_fitness', 'misc_pos', 'travel',
    'kids_pets', 'shopping_pos', 'food_dining', 'home',
    'entertainment', 'shopping_net', 'misc_net', 'grocery_pos',
    'gas_transport', 'grocery_net'
]

# Define merchant options
merchant_options = ['fraud_Kirlin and Sons', 'fraud_Sporer-Keebler',
       'fraud_Swaniawski, Nitzsche and Welch', 'fraud_Haley Group',
       'fraud_Johnston-Casper', 'fraud_Daugherty LLC',
       'fraud_Romaguera Ltd', 'fraud_Reichel LLC',
       'fraud_Goyette, Howell and Collier', 'fraud_Kilback Group',
       'fraud_Feil, Hilpert and Koss', 'fraud_Gottlieb Group',
       'fraud_Connelly-Carter', 'fraud_Bechtelar-Rippin',
       'fraud_Lubowitz-Walter', 'fraud_Welch, Rath and Koepp',
       'fraud_Hickle Group', 'fraud_Lang, Towne and Schuppe',
       'fraud_Morissette LLC', 'fraud_Prosacco LLC',
       'fraud_Corwin-Romaguera', 'fraud_Tillman LLC',
       'fraud_Veum-Koelpin', 'fraud_Watsica, Haag and Considine',
       'fraud_Leannon-Ward', 'fraud_Hintz, Bauch and Smith',
       'fraud_Labadie LLC', 'fraud_Eichmann, Hayes and Treutel',
       'fraud_Leffler-Goldner', 'fraud_Kautzer and Sons',
       'fraud_Ernser-Feest', 'fraud_Zemlak, Tillman and Cremin',
       'fraud_Nienow PLC', 'fraud_Lynch-Wisozk', 'fraud_Schiller Ltd',
       'fraud_Hoppe-Parisian', 'fraud_Brown-Greenholt',
       'fraud_Reilly LLC', 'fraud_Moore, Williamson and Emmerich',
       'fraud_Rau-Robel', 'fraud_Fadel, Mertz and Rippin',
       'fraud_Crona and Sons', 'fraud_Bahringer, Bergnaum and Quitzon',
       'fraud_Koss, Hansen and Lueilwitz',
       'fraud_Yost, Schamberger and Windler',
       'fraud_Armstrong, Walter and Gottlieb', 'fraud_Friesen Ltd',
       'fraud_Champlin and Sons', 'fraud_Bins-Tillman',
       'fraud_Douglas-White', 'fraud_Hermiston, Pacocha and Smith',
       'fraud_Denesik, Powlowski and Pouros', 'fraud_Nader-Maggio',
       "fraud_O'Reilly, Mohr and Purdy", "fraud_O'Connell-Ullrich",
       'fraud_Bauch-Blanda', 'fraud_Ruecker, Beer and Collier',
       'fraud_Berge-Hills', 'fraud_White and Sons', 'fraud_Adams-Barrows',
       'fraud_Pouros-Haag', 'fraud_Hahn, Bahringer and McLaughlin',
       'fraud_Ziemann-Waters', 'fraud_Wuckert, Wintheiser and Friesen',
       'fraud_Bednar PLC', 'fraud_Kihn Inc', 'fraud_Fisher Inc',
       'fraud_Schneider, Hayes and Nikolaus',
       "fraud_Greenholt, O'Hara and Balistreri", 'fraud_Gottlieb-Hansen',
       'fraud_Douglas, Schneider and Turner',
       'fraud_Gutmann, McLaughlin and Wiza', 'fraud_Weber and Sons',
       'fraud_Bartoletti and Sons', 'fraud_Powlowski-Weimann',
       'fraud_Lakin, Ferry and Beatty', 'fraud_Terry, Johns and Bins',
       'fraud_Thiel-Thiel', 'fraud_Kuhn Group',
       'fraud_Schaefer, Fay and Hilll', 'fraud_Roberts, Ryan and Smith',
       'fraud_Stiedemann Ltd', 'fraud_Pacocha-Weissnat',
       'fraud_Homenick LLC', 'fraud_Cartwright PLC', 'fraud_Kihn-Fritsch',
       'fraud_Lynch Ltd', 'fraud_Klein Group', 'fraud_Quitzon-Goyette',
       'fraud_Greenholt Ltd', 'fraud_Bahringer Group',
       'fraud_Hilpert-Conroy', 'fraud_Witting, Beer and Ernser',
       'fraud_Breitenberg-Hermiston', 'fraud_Friesen Inc',
       'fraud_Baumbach, Strosin and Nicolas', 'fraud_Rippin-VonRueden',
       'fraud_Nienow, Ankunding and Collier', 'fraud_Schmidt and Sons',
       'fraud_Prosacco, Kreiger and Kovacek', 'fraud_Schumm PLC',
       'fraud_Berge-Ullrich', 'fraud_Roob, Conn and Tremblay',
       'fraud_Kihn-Schuster', 'fraud_Monahan-Morar', 'fraud_Botsford Ltd',
       "fraud_Hamill-D'Amore", 'fraud_Bradtke, Torp and Bahringer',
       'fraud_Gaylord-Powlowski', 'fraud_Mayert Group',
       'fraud_Beier and Sons', 'fraud_Abbott-Steuber',
       'fraud_Ernser-Lynch', 'fraud_Little Ltd', 'fraud_Gislason Group',
       'fraud_Stark-Koss', 'fraud_Crist, Jakubowski and Littel',
       'fraud_Kling-Ernser', 'fraud_Cronin, Kshlerin and Weber',
       'fraud_Upton PLC', 'fraud_Carroll PLC', 'fraud_Effertz LLC',
       'fraud_Windler LLC', 'fraud_Satterfield-Lowe',
       'fraud_Schuppe-Schuppe', 'fraud_Nader-Heller', 'fraud_Auer-West',
       "fraud_Lesch, D'Amore and Brown", 'fraud_Barrows PLC',
       "fraud_O'Connell, Botsford and Hand", 'fraud_Bode-Schuster',
       "fraud_O'Keefe-Wisoky", 'fraud_Conroy-Emard', 'fraud_Kutch-Ferry',
       'fraud_Donnelly LLC', 'fraud_Weimann-Lockman', 'fraud_Runte-Mohr',
       'fraud_Dare, Fritsch and Zboncak',
       'fraud_Kihn, Brakus and Goyette', 'fraud_Medhurst PLC',
       'fraud_Waelchi Inc', 'fraud_Dickinson Ltd',
       'fraud_Little, Gutmann and Lynch', 'fraud_Schaefer Ltd',
       'fraud_Ankunding LLC', 'fraud_Schoen-Quigley', 'fraud_Towne LLC',
       'fraud_Hills, Hegmann and Schaefer',
       'fraud_Durgan, Gislason and Spencer',
       'fraud_Hauck, Dietrich and Funk',
       'fraud_Lubowitz, Terry and Stracke', 'fraud_Erdman-Ebert',
       'fraud_Kub PLC', 'fraud_Lehner, Reichert and Mills',
       'fraud_Schiller, Blanda and Johnson', 'fraud_Bins-Howell',
       'fraud_Turcotte, Batz and Buckridge', 'fraud_Will Ltd',
       'fraud_Gibson-Deckow', 'fraud_Treutel-King',
       'fraud_Schmidt-Larkin', 'fraud_Windler, Goodwin and Kovacek',
       'fraud_Medhurst Inc', 'fraud_Breitenberg LLC', 'fraud_Terry Ltd',
       'fraud_Runte, Green and Emard', 'fraud_Feil-Morar',
       'fraud_Kilback and Sons', 'fraud_Conroy, Balistreri and Gorczany',
       'fraud_Schuppe LLC', 'fraud_Renner Ltd',
       'fraud_Romaguera, Wehner and Tromp', 'fraud_McKenzie-Huels',
       'fraud_Dare-Marvin', 'fraud_Gleason and Sons',
       'fraud_Cole, Hills and Jewess', 'fraud_Roob-Okuneva',
       'fraud_Padberg-Sauer', 'fraud_Gerhold LLC',
       'fraud_Botsford and Sons', 'fraud_Volkman-Predovic',
       'fraud_Dare-Gibson', 'fraud_Rempel Inc', 'fraud_Torphy-Kertzmann',
       'fraud_Runolfsdottir, Mueller and Hand',
       'fraud_Torp, Muller and Borer', 'fraud_Abshire PLC',
       'fraud_Spencer-Runolfsson', 'fraud_Streich Ltd',
       'fraud_Bernier and Sons', 'fraud_Dare, Casper and Bartoletti',
       'fraud_Zboncak LLC', 'fraud_Erdman-Durgan', 'fraud_Thiel Ltd',
       'fraud_Heathcote LLC', 'fraud_Eichmann-Kilback',
       'fraud_Hoppe, Harris and Bednar', 'fraud_Hammes-Beatty',
       'fraud_Jacobi and Sons', 'fraud_Jast and Sons',
       'fraud_Streich, Rolfson and Wilderman', 'fraud_Zboncak Ltd',
       'fraud_Lemke and Sons', 'fraud_Kulas Group', 'fraud_Goldner-Lemke',
       'fraud_Predovic Inc', 'fraud_Howe Ltd', 'fraud_Stoltenberg-Beatty',
       'fraud_Bruen-Yost', 'fraud_Reichel, Bradtke and Blanda',
       'fraud_Morissette PLC', 'fraud_Reichert, Huels and Hoppe',
       'fraud_Hills-Witting', 'fraud_Shanahan-Lehner',
       'fraud_Bogisich-Weimann', 'fraud_Douglas, DuBuque and McKenzie',
       'fraud_Daugherty-Thompson', 'fraud_Goyette-Herzog',
       'fraud_Keeling-Crist', 'fraud_Walter, Hettinger and Kessler',
       'fraud_Kozey-McDermott', 'fraud_McDermott, Osinski and Morar',
       'fraud_Kilback, Nitzsche and Leffler', 'fraud_Vandervort-Funk',
       'fraud_Hills-Boyer', 'fraud_Jast Ltd', 'fraud_Grimes LLC',
       'fraud_Gulgowski LLC', 'fraud_Mohr-Bayer',
       'fraud_Bahringer, Osinski and Block', 'fraud_Simonis-Prohaska',
       'fraud_Kunze, Larkin and Mayert',
       'fraud_Becker, Harris and Harvey', 'fraud_Kutch-Wilderman',
       'fraud_Lehner, Mosciski and King', 'fraud_Heaney-Marquardt',
       'fraud_McCullough, Hudson and Schuster', 'fraud_Kilback LLC',
       'fraud_Kub-Heaney', 'fraud_Schumm, McLaughlin and Carter',
       'fraud_Heller PLC', 'fraud_Hahn, Douglas and Schowalter',
       'fraud_Kertzmann LLC', 'fraud_Mueller, Gerhold and Mueller',
       'fraud_Reinger, Weissnat and Strosin', 'fraud_Connelly PLC',
       'fraud_Conroy Ltd', 'fraud_Willms, Kris and Bergnaum',
       'fraud_Pouros, Walker and Spencer',
       'fraud_Roberts, Daniel and Macejkovic',
       'fraud_Heathcote, Yost and Kertzmann', 'fraud_Larkin Ltd',
       'fraud_Metz-Boehm', 'fraud_Parker-Kunde', 'fraud_Yost-Rogahn',
       'fraud_Crooks and Sons', 'fraud_Nienow, Barrows and Romaguera',
       'fraud_Gleason-Macejkovic', 'fraud_Altenwerth-Kilback',
       'fraud_Kuphal-Toy', 'fraud_Schulist Ltd', 'fraud_Welch Inc',
       'fraud_Kassulke PLC', 'fraud_Rau-Grant', 'fraud_Macejkovic-Lesch',
       'fraud_Graham, Hegmann and Hammes', 'fraud_Waters-Cruickshank',
       'fraud_Lesch Ltd', 'fraud_Kozey-Boehm', 'fraud_Bode-Rempel',
       'fraud_Romaguera, Cruickshank and Greenholt', 'fraud_Howe PLC',
       'fraud_Volkman PLC', 'fraud_Quitzon, Green and Bashirian',
       'fraud_Shields-Wunsch', 'fraud_Williamson LLC', 'fraud_Fadel Inc',
       'fraud_Pacocha-Bauch', 'fraud_Fisher-Schowalter',
       'fraud_Johns Inc', 'fraud_Nolan-Williamson', 'fraud_Maggio-Fahey',
       'fraud_Denesik and Sons', 'fraud_Jast-McDermott',
       'fraud_Price Inc', 'fraud_Schoen Ltd', 'fraud_Fahey Inc',
       'fraud_Stiedemann Inc', 'fraud_Mohr Inc', 'fraud_Wisozk and Sons',
       'fraud_Rolfson-Kunde', 'fraud_Wuckert-Goldner',
       'fraud_Pouros-Conroy', 'fraud_Kuhn LLC', 'fraud_Skiles LLC',
       'fraud_Boyer PLC', 'fraud_Reilly and Sons', 'fraud_Ratke and Sons',
       'fraud_Emmerich-Rau', 'fraud_Marvin-Lind', 'fraud_Wiza LLC',
       'fraud_Torp-Lemke', 'fraud_Effertz, Welch and Schowalter',
       'fraud_Jerde-Hermann', 'fraud_Kassulke Inc',
       'fraud_Ankunding-Carroll', 'fraud_Waelchi-Wolf', 'fraud_Pagac LLC',
       'fraud_Cormier LLC', 'fraud_Larkin, Stracke and Greenfelder',
       'fraud_Ebert-Daugherty', 'fraud_Rohan, White and Aufderhar',
       'fraud_Schmeler-Howe', 'fraud_Osinski Inc',
       'fraud_Bernhard, Grant and Langworth',
       'fraud_Hagenes, Kohler and Hoppe',
       'fraud_Klocko, Runolfsdottir and Breitenberg',
       'fraud_Larson, Quitzon and Spencer',
       'fraud_Weber, Thiel and Hammes', 'fraud_Christiansen-Gusikowski',
       'fraud_Morissette-Schaefer', 'fraud_Watsica LLC',
       'fraud_Jakubowski Group', 'fraud_Herzog Ltd',
       'fraud_Hackett Group', 'fraud_Reichel Inc',
       'fraud_Abernathy and Sons', 'fraud_Stark-Batz',
       'fraud_Konopelski, Schneider and Hartmann',
       'fraud_Ledner, Hartmann and Feest', 'fraud_Champlin-Casper',
       'fraud_Goyette-Gerhold', 'fraud_Kihn, Abernathy and Douglas',
       'fraud_Stanton, Jakubowski and Baumbach', 'fraud_Terry-Huel',
       'fraud_Cummerata-Hilpert', 'fraud_Turner and Sons',
       'fraud_Bahringer, Schoen and Corkery',
       'fraud_Hettinger, McCullough and Fay',
       'fraud_Hayes, Marquardt and Dibbert', 'fraud_Zulauf LLC',
       'fraud_Dibbert-Green', 'fraud_Brown Inc', 'fraud_Fadel-Hilpert',
       'fraud_Turner, Ziemann and Lehner', 'fraud_Fritsch LLC',
       'fraud_Labadie, Treutel and Bode',
       'fraud_Hodkiewicz, Prohaska and Paucek', 'fraud_Swift PLC',
       'fraud_Little-Gleichner', 'fraud_Stamm-Witting',
       'fraud_Zboncak, Rowe and Murazik', 'fraud_Baumbach Ltd',
       'fraud_Lowe, Dietrich and Erdman',
       'fraud_Hermiston, Russel and Price', 'fraud_Auer LLC',
       'fraud_Fritsch and Sons', 'fraud_Wilkinson PLC',
       'fraud_Jakubowski Inc', 'fraud_Boyer-Reichert',
       'fraud_Boyer-Haley', 'fraud_Dietrich-Fadel',
       'fraud_Haley, Jewess and Bechtelar', 'fraud_McGlynn-Jaskolski',
       'fraud_Turcotte, McKenzie and Koss',
       'fraud_Cormier, Stracke and Thiel',
       'fraud_Baumbach, Feeney and Morar', 'fraud_Turcotte-Halvorson',
       'fraud_Hyatt-Blick', 'fraud_Bernier, Volkman and Hoeger',
       'fraud_Gottlieb, Considine and Schultz', 'fraud_Frami Group',
       'fraud_Lebsack and Sons', 'fraud_Haley, Batz and Auer',
       'fraud_Beier-Hyatt', 'fraud_Halvorson Group', 'fraud_Johns-Hoeger',
       'fraud_Schroeder Group', 'fraud_Weimann, Kuhic and Beahan',
       'fraud_Kozey-Kuhlman', 'fraud_Kris-Padberg',
       'fraud_Dibbert and Sons', 'fraud_Collier LLC', 'fraud_Bednar Inc',
       'fraud_Durgan-Auer', 'fraud_Murray-Smitham',
       'fraud_Kling, Howe and Schneider', 'fraud_Larson-Moen',
       'fraud_Cruickshank-Mills', 'fraud_Berge, Kautzer and Harris',
       "fraud_O'Hara-Wilderman", 'fraud_Hyatt, Russel and Gleichner',
       'fraud_Bins, Balistreri and Beatty', 'fraud_Jewess LLC',
       'fraud_Hartmann, Rowe and Hermann', 'fraud_Buckridge PLC',
       'fraud_Langworth LLC', 'fraud_Metz, Russel and Metz',
       'fraud_Schoen, Kuphal and Nitzsche', 'fraud_Erdman-Schaden',
       'fraud_Reichert-Weissnat', 'fraud_McDermott-Rice',
       'fraud_Streich, Dietrich and Barton', 'fraud_Gerlach Inc',
       'fraud_Dooley Inc', 'fraud_Thompson-Gleason',
       'fraud_Reichert, Shanahan and Hayes',
       'fraud_Kutch, Steuber and Gerhold', 'fraud_Harris Group',
       'fraud_Schuppe, Nolan and Hoeger', 'fraud_Bashirian Group',
       'fraud_Towne, Greenholt and Koepp', 'fraud_Haag-Blanda',
       'fraud_Abbott-Rogahn', 'fraud_Lind-Buckridge',
       'fraud_Altenwerth, Cartwright and Koss',
       'fraud_Daugherty, Pouros and Beahan',
       'fraud_Langosh, Wintheiser and Hyatt', 'fraud_Beier LLC',
       'fraud_Brown, Homenick and Lesch', 'fraud_Spencer PLC',
       'fraud_Ritchie, Oberbrunner and Cremin', 'fraud_Kovacek Ltd',
       'fraud_Pollich LLC', 'fraud_Baumbach, Hodkiewicz and Walsh',
       'fraud_Koss, McLaughlin and Mayer', 'fraud_Kessler Group',
       'fraud_Smith-Stokes', 'fraud_Herman Inc', 'fraud_Kuhic LLC',
       'fraud_Pfeffer and Sons', 'fraud_Botsford PLC',
       'fraud_Schoen, Nienow and Bauch', 'fraud_Turner LLC',
       'fraud_Parker, Nolan and Trantow',
       'fraud_Ritchie, Bradtke and Stiedemann', 'fraud_Ruecker-Mayert',
       'fraud_Ullrich Ltd', 'fraud_Schmeler, Bashirian and Price',
       'fraud_Mosciski Group', 'fraud_Boehm, Block and Jakubowski',
       'fraud_Deckow-Dare', 'fraud_Beer-Jast', 'fraud_Schimmel-Olson',
       'fraud_Schmeler Inc', 'fraud_Thiel PLC',
       'fraud_Boehm, Predovic and Reinger', 'fraud_Graham and Sons',
       'fraud_McCullough LLC', 'fraud_Mosciski, Gislason and Mertz',
       'fraud_Schroeder, Hauck and Treutel', 'fraud_Block-Parisian',
       'fraud_Flatley Group', 'fraud_McLaughlin, Armstrong and Koepp',
       'fraud_Wilkinson LLC', 'fraud_Sawayn PLC', 'fraud_Eichmann-Russel',
       'fraud_Hermann and Sons', 'fraud_Goyette Inc', 'fraud_Barton LLC',
       'fraud_Yost, Block and Koepp', 'fraud_Kerluke-Abshire',
       'fraud_Padberg-Rogahn', 'fraud_Dach-Nader',
       'fraud_Wintheiser, Dietrich and Schimmel',
       'fraud_Champlin, Rolfson and Connelly', 'fraud_Jacobi Inc',
       'fraud_Koelpin and Sons', 'fraud_Medhurst, Labadie and Gottlieb',
       'fraud_Bednar Group', 'fraud_Friesen-Ortiz',
       'fraud_Turner, Ruecker and Parisian', 'fraud_Rutherford-Mertz',
       'fraud_Gutmann-Upton', 'fraud_Medhurst, Cartwright and Ebert',
       'fraud_Nicolas, Hills and McGlynn',
       'fraud_Nitzsche, Kessler and Wolff', 'fraud_Wilkinson Ltd',
       'fraud_Kris-Kertzmann', 'fraud_Roberts-Beahan',
       'fraud_Bernhard-Lesch', 'fraud_Monahan, Bogisich and Ledner',
       'fraud_Kessler Inc', 'fraud_Padberg-Welch', 'fraud_Block Group',
       'fraud_Torphy-Goyette', 'fraud_Mante, Luettgen and Hackett',
       'fraud_Bailey-Morar', 'fraud_Lynch-Mohr',
       'fraud_Rodriguez, Yost and Jenkins', 'fraud_Stamm-Rodriguez',
       'fraud_Okuneva, Schneider and Rau', 'fraud_Hirthe-Beier',
       'fraud_Tromp Group', 'fraud_Schroeder, Wolff and Hermiston',
       'fraud_Reichert, Rowe and Mraz', 'fraud_Bahringer-Streich',
       'fraud_Romaguera and Sons', 'fraud_Lemke-Gutmann',
       'fraud_Heller-Langosh', 'fraud_Hintz-Bruen',
       'fraud_McGlynn-Heathcote', 'fraud_Bernhard Inc',
       'fraud_Bahringer-Larson', 'fraud_Reilly, Heaney and Cole',
       'fraud_Bernier, Streich and Jewess', "fraud_Friesen-D'Amore",
       'fraud_Huel, Hammes and Witting', 'fraud_Miller-Hauck',
       'fraud_Skiles-Ankunding', 'fraud_Schmitt Ltd', 'fraud_Kerluke Inc',
       'fraud_Volkman Ltd', 'fraud_Prohaska-Murray', 'fraud_Schmitt Inc',
       'fraud_Kerluke, Considine and Macejkovic', 'fraud_Kutch-Hegmann',
       'fraud_Spinka Inc', 'fraud_Stracke-Lemke',
       'fraud_Raynor, Feest and Miller', 'fraud_Strosin-Cruickshank',
       'fraud_Schaefer, McGlynn and Bosco', 'fraud_Marks Inc',
       'fraud_Huel-Langworth', 'fraud_Eichmann, Bogan and Rodriguez',
       'fraud_Morissette, Weber and Wiegand',
       'fraud_Moen, Reinger and Murphy',
       'fraud_Schultz, Simonis and Little',
       'fraud_Ferry, Lynch and Kautzer',
       'fraud_Osinski, Ledner and Leuschke', 'fraud_Ledner-Pfannerstill',
       "fraud_O'Keefe-Hudson", 'fraud_Murray Ltd', 'fraud_Pfeffer LLC',
       'fraud_Cole PLC', 'fraud_Hudson-Ratke', 'fraud_Kuvalis Ltd',
       'fraud_Miller-Harris', 'fraud_Zieme, Bode and Dooley',
       'fraud_Swaniawski, Lowe and Robel', 'fraud_Kemmer-Buckridge',
       'fraud_Swift, Bradtke and Marquardt',
       'fraud_Olson, Becker and Koch', 'fraud_Bartoletti-Wunsch',
       'fraud_Emard Inc', 'fraud_Ferry, Reichel and DuBuque',
       'fraud_Kemmer-Reinger', 'fraud_Koss and Sons',
       'fraud_Hackett-Lueilwitz', 'fraud_Barton Inc', 'fraud_Lockman Ltd',
       'fraud_Klocko LLC', 'fraud_Kunze Inc', 'fraud_Luettgen PLC',
       'fraud_Cummerata-Jones', 'fraud_Rowe, Batz and Goodwin',
       'fraud_Kling Inc', 'fraud_Kiehn-Emmerich',
       'fraud_Parisian and Sons', 'fraud_Sporer Inc',
       'fraud_Kuphal-Bartoletti', 'fraud_Harris, Gusikowski and Heaney',
       'fraud_Mraz-Herzog', 'fraud_Huels-Hahn',
       'fraud_Stroman, Hudson and Erdman', 'fraud_Huel Ltd',
       'fraud_Cremin, Hamill and Reichel', 'fraud_Rowe-Vandervort',
       'fraud_Bins-Rice', 'fraud_DuBuque LLC', 'fraud_Torp-Labadie',
       'fraud_Kiehn Inc', 'fraud_Tillman, Dickinson and Labadie',
       'fraud_Friesen-Stamm', 'fraud_Kuhic Inc', 'fraud_Dickinson-Rempel',
       'fraud_Hudson-Grady', 'fraud_Goldner, Kovacek and Abbott',
       'fraud_Corwin-Collins', 'fraud_Tillman, Fritsch and Schmitt',
       'fraud_Dach-Borer', 'fraud_Morar Inc',
       'fraud_Kutch, Hermiston and Farrell',
       'fraud_Connelly, Reichert and Fritsch',
       "fraud_Schamberger-O'Keefe", 'fraud_McDermott-Weimann',
       'fraud_Kerluke PLC', 'fraud_Casper, Hand and Zulauf',
       'fraud_Greenfelder, Bartoletti and Davis',
       'fraud_Cartwright-Harris', 'fraud_Rau and Sons',
       'fraud_Erdman-Kertzmann', 'fraud_Hamill-Daugherty',
       'fraud_Jaskolski-Vandervort', 'fraud_Huels-Nolan',
       'fraud_Trantow PLC', 'fraud_Lockman, West and Runte',
       'fraud_Johnson, Runolfsdottir and Mayer',
       'fraud_Kovacek, Dibbert and Ondricka',
       'fraud_Raynor, Reinger and Hagenes', 'fraud_Kutch LLC',
       'fraud_Dooley-Thompson', 'fraud_Harber Inc',
       'fraud_Schumm, Bauch and Ondricka',
       'fraud_Moore, Dibbert and Koepp', 'fraud_Flatley-Durgan',
       'fraud_Rodriguez Group', 'fraud_Stokes, Christiansen and Sipes',
       'fraud_Heidenreich PLC', 'fraud_Bauch-Raynor',
       'fraud_Langworth, Boehm and Gulgowski',
       'fraud_Runolfsson and Sons', 'fraud_Ortiz Group',
       'fraud_Zemlak Group', 'fraud_Wuckert-Walter',
       'fraud_Tromp, Kerluke and Glover', 'fraud_Ruecker Group',
       "fraud_Deckow-O'Conner", 'fraud_Heller, Gutmann and Zieme',
       'fraud_Robel, Cummerata and Prosacco',
       'fraud_Lind, Huel and McClure', 'fraud_Roob LLC',
       'fraud_VonRueden Group', 'fraud_Wolf Inc', 'fraud_Kutch and Sons',
       'fraud_Gutmann Ltd', 'fraud_Jones, Sawayn and Romaguera',
       'fraud_Brekke and Sons', 'fraud_Adams, Kovacek and Kuhlman',
       'fraud_Collier Inc', 'fraud_Greenholt, Jacobi and Gleason',
       'fraud_Stehr, Jewess and Schimmel', 'fraud_Koepp-Witting',
       'fraud_Cummings LLC', 'fraud_Wiegand-Lowe', 'fraud_Paucek-Wiza',
       'fraud_Conroy-Cruickshank', 'fraud_Bogisich-Homenick',
       'fraud_Jenkins, Hauck and Friesen', 'fraud_Emmerich-Luettgen',
       'fraud_Cassin-Harvey', 'fraud_Schaefer, Maggio and Daugherty',
       'fraud_Kohler, Lindgren and Koelpin', 'fraud_Doyle Ltd',
       'fraud_Heller-Abshire', 'fraud_Mosciski, Ziemann and Farrell',
       'fraud_Cummings Group', 'fraud_Swaniawski, Bahringer and Ledner',
       'fraud_Christiansen, Goyette and Schamberger', 'fraud_Bradtke PLC',
       'fraud_Streich, Hansen and Veum', "fraud_Pacocha-O'Reilly",
       'fraud_Koepp-Parker', 'fraud_Auer-Mosciski',
       'fraud_Wiza, Schaden and Stark', 'fraud_Kuhic, Bins and Pfeffer',
       'fraud_Bogisich Inc', 'fraud_Kling-Grant', 'fraud_Kutch Group',
       'fraud_Kuphal-Predovic', 'fraud_Balistreri-Nader',
       'fraud_Harris Inc', 'fraud_Berge LLC',
       'fraud_Towne, Walker and Borer',
       'fraud_Herman, Treutel and Dickens', 'fraud_Kris-Weimann',
       'fraud_Reynolds-Schinner', 'fraud_Goodwin-Nitzsche',
       'fraud_Jaskolski-Dibbert', 'fraud_Dicki Ltd', 'fraud_Funk Group',
       'fraud_Rutherford, Homenick and Bergstrom',
       'fraud_Kerluke, Kertzmann and Wiza', 'fraud_Donnelly PLC',
       'fraud_Spinka-Welch', 'fraud_Brown PLC', 'fraud_Kunde-Sanford',
       'fraud_Parisian, Schiller and Altenwerth', 'fraud_Smitham-Boehm',
       'fraud_Shields Inc', 'fraud_Johnston, Nikolaus and Maggio',
       'fraud_Smitham-Schiller', 'fraud_Hills-Olson',
       'fraud_Rippin, Kub and Mann', 'fraud_Rempel PLC',
       'fraud_Leannon-Nikolaus', 'fraud_Monahan, Hermann and Johns',
       'fraud_Block-Hauck', 'fraud_Hagenes, Hermann and Stroman',
       'fraud_Hermann-Gaylord', 'fraud_Mante Group',
       'fraud_Corwin-Gorczany', 'fraud_McCullough Group']

# Use dropdowns for merchant and category instead of text inputs
merchant = st.selectbox('Merchant', merchant_options)
category = st.selectbox('Category', category_options)
gender = st.selectbox('Gender', ['M', 'F'])
cc_num = st.number_input('Credit Card Number', min_value=0, format="%d")
amt = st.number_input('Transaction Amount', min_value=0.0, format="%.2f")

lat = st.number_input('Latitude', format="%.6f")
long = st.number_input('Longitude', format="%.6f")
city_pop = st.number_input('City Population', min_value=0)

unix_time = st.number_input('Transaction Unix Time (epoch)', min_value=0, format="%d")

merch_lat = st.number_input('Merchant Latitude', format="%.6f")
merch_long = st.number_input('Merchant Longitude', format="%.6f")

hour = st.slider('Transaction Hour', 0, 23, 12)
dayofweek = st.slider('Day of Week (0=Monday)', 0, 6, 3)
age = st.number_input('Customer Age', min_value=0, max_value=120, value=30)

# Predict on button click
if st.button('Predict Fraud'):
    input_dict = {
        'merchant': [merchant],
        'category': [category],
        'gender': [gender],
        'cc_num': [cc_num],
        'amt': [amt],
        'lat': [lat],
        'long': [long],
        'city_pop': [city_pop],
        'unix_time': [unix_time],
        'merch_lat': [merch_lat],
        'merch_long': [merch_long],
        'hour': [hour],
        'dayofweek': [dayofweek],
        'age': [age]
    }

    input_df = pd.DataFrame(input_dict)

    # Predict label and probability
    prediction = model.predict(input_df)[0]
    prob = model.predict_proba(input_df)[0][1]

    if prediction == 1:
        st.error(f"⚠️ Fraudulent Transaction detected! Confidence: {prob:.2%}")
    else:
        st.success(f"✅ Transaction appears genuine. Confidence: {(1 - prob):.2%}")
